### ISSUE TITLE
Train - Traitement des lignes identiques

### ISSUE THREAD

**Issue by Jojooct10** [entrepreneur-interet-general/the-magical-csv-merge-machine#58]
Impression que l'algo ne vérifie pas que les lignes sont doublonnées. Dommage on perd du temps et on ouvre la porte à incohérences

**Comment by Leobouloc** [comment]
Tu parles de doublons de la source ou du référentiel ?

Normalement, **la source** est dédoublonnée avant la labellisation, mais pas le référentiel (il ne devrait pas en contenir à la base; le problème est si l'on restreint les champs...).
