### ISSUE TITLE
Plantage après 120 labellisation

### ISSUE THREAD

**Issue by Jojooct10** [entrepreneur-interet-general/the-magical-csv-merge-machine#61]
Reprise d'un projet de labellisation sur SIRENE+Essais cliniques. Les 20-30 premiers trains ont fonctionné puis plantage
Impossible de passer à exemple de train suivant
Mais possible de cliquer sur terminer mais tourne dans le vide

![image](https://user-images.githubusercontent.com/34550712/34095229-ecf55732-e3d0-11e7-8f62-90f4a18eda05.png)

**Comment by Leobouloc** [comment]
pas reproduit depuis quelques temps. rouvrir si nécessaire.
