### ISSUE TITLE
Pb restitution des résultats après labellisation

### ISSUE THREAD

**Issue by Jojooct10** [entrepreneur-interet-general/the-magical-csv-merge-machine#63]
Le Vrai/faux ne semble pas marcher et les indices de confiance semblent improbables. Malgré cela, les propositions d'association sont plutôt bonnes

![image](https://user-images.githubusercontent.com/34550712/34469292-27c31538-ef1c-11e7-9ff8-6255e79979dc.png)

**Comment by Leobouloc** [comment]
https://github.com/entrepreneur-interet-general/the-magical-csv-merge-machine/commit/c94d5add8c4d67bf4f18327e1e18615d64391c19
