### ISSUE TITLE
Valeur étonnante du taux de couverture

### ISSUE THREAD

**Issue by Jojooct10** [entrepreneur-interet-general/the-magical-csv-merge-machine#64]
Après plus de 500 actions de labellisation bonnes ou mauvaises. Le taux de couverture flirte toujours autour de la valeur 62% (ou 39%). Un peu étonnant ces valeurs récurrentes et éloignées

**Comment by Leobouloc** [comment]
Sur un même fichier, ou bien sur tous les fichiers en général. Si c'est sur le même fichier, tu obtiens ces chiffres en gardant à chaque fois les mêmes associations de colonnes ?

**Comment by Leobouloc** [comment]
Problem with the query info in `to_emit`. Solved.
